services:
  krakend:
    image: devopsfaith/krakend
    depends_on:
      - influxdb
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - ./krakend/krakend/config:/etc/krakend
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    networks:
      - apigateway
  influxdb:
    image: influxdb:1.8
    environment:
      - "INFLUXDB_DB=krakend"
      - "INFLUXDB_USER=krakend-dev"
      - "INFLUXDB_USER_PASSWORD=pas5w0rd"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=supersecretpassword"
    ports:
      - "8086:8086"
    volumes:
      - ./krakend/influxdb/data:/var/lib/influxdb
    networks:
      - apigateway
  grafana:
    build: ./krakend/grafana
    depends_on:
      - influxdb
    ports:
      - "3001:3000"
    networks:
      - apigateway
  jaeger:
    image: jaegertracing/all-in-one:latest
    depends_on:
      - krakend
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - apigateway

networks:
  apigateway:
    driver: bridge
